parameters: 
- name: env 
  displayName: Environment
  type: string 
  default: "stg" 

schedules: 
- cron: '0 0 * * 0'
  displayName: Weekly midnight build 
  branches: 
   include: 
   - main 

variables: 
  - name: ghcr_image 
    value: "ghcr.io/foxglove/studio:latest" 
  - name: app_name 
    value: "studio" 
  - name: image_repository 
    value: "foxglove"  
  - name: tags 
    value: $(Build.BuildId) 
  - name: acr_service_connection 
    value: "acr_service_connection_${{ parameters.env }}" 

stages: 
  - stage: "TransferimagefromGHCRtoACR" 
    jobs: 
    - job: "imgpullacr" 
      pool: 
        vmImage: "Ubuntu-latest" 
      steps: 
        - script: | 
            docker pull $(ghcr_image) 
          displayName: Pull Foxglove image from GHCR
        - script : |
            docker tag $(ghcr_image) $(acr_service_connection)/$(app_name):$(Build.BuildId)
          displayName: tagging local Foxglove image
        - task: Docker@2 
          displayName: Login to ACR 
          inputs: 
            command: "login" 
            containerRegistry: $(acr_service_connection) 
        - task: Docker@2 
          displayName: Push image to ACR 
          inputs: 
            command: "push" 
            containerRegistry: $(acr_service_connection) 
            repository: $(app_name) 
            tags: $(tags)