parameters:
- name: env
  displayName: Environment
  values:
  - dev
  - test

trigger:
  batch: false
  branches:
    include:
      - main

pr:
   branches:
     include:
     - main
pool:
  vmImage: 'ubuntu-latest'


variables:
  - name: adf_code_path
    value: "$(Build.SourcesDirectory)/adf"
    
  - name: adf_package_file_path
    value: "$(Build.SourcesDirectory)/adf/.pipelines/"
  
  - name: arm_service_connection
    value: "arm_service_connection_${{ parameters.env }}"


# Installs Node and the npm packages saved in package.json files in the build folder
stages:
  - stage: Build_And_Publish_ADF_Artifacts
    
    jobs:
    - job: Build_Adf_Arm_Templates
      displayName: 'Generate ADF Artifacts'
      steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(adf_package_file_path)'
          verbose: true
        displayName: 'Install npm package'


      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(adf_package_file_path)'

          customCommand: 'run build validate $(adf_code_path) /subscriptions/$(azure_subscription_id)/resourceGroups/$(resource_group_name)/providers/Microsoft.DataFactory/factories/$(azure_data_factory_name)'
        displayName: 'Validate'

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(adf_package_file_path)'

          customCommand: 'run build export $(adf_code_path) /subscriptions/$(azure_subscription_id)/resourceGroups/$(resource_group_name)/providers/Microsoft.DataFactory/factories/$(azure_data_factory_name) "ArmTemplate"'

        displayName: 'Validate and Generate ARM template'


      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(adf_code_path)/.pipelines/ArmTemplate'
          artifact: 'adf-artifact-$(Build.BuildNumber)'
          publishLocation: 'pipeline'
          
  - stage: Deploy_to_Dev
    displayName: Deploy Stage
    dependsOn: Build_And_Publish_ADF_Artifacts
    jobs: 
      - job: Deploy_PreProd
        displayName: 'Deployment'
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: Download Build Artifacts - ADF ARM templates
          inputs: 
            artifactName: 'adf-artifact-$(Build.BuildNumber)'
            targetPath: '$(Pipeline.Workspace)/adf-artifact-$(Build.BuildNumber)'
        
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(arm_service_connection)'
            subscriptionId: '$(azure_subscription_id)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'rg-avdataops-${{ parameters.env }}'
            location: '$(location)'
            templateLocation: 'Linked artifact'
            csmFile: '$(Pipeline.Workspace)/adf-artifact-$(Build.BuildNumber)/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/adf-artifact-$(Build.BuildNumber)/ARMTemplateParametersForFactory.json'
            overrideParameters: '-factoryName "$(azure_data_factory_name)" -keyvault_connection_properties_typeProperties_baseUrl "https://$(azure_keyvault_name).vault.azure.net/"'
            deploymentMode: 'Incremental'