parameters: 
- name: env 
  displayName: Environment
  type: string 
  default: "stg" 

variables: 
  - name: ghcr_image 
    value: "ghcr.io/foxglove/studio:latest" 
  - name: containerRegistry
    value:  "acravdataopshiniv.azurecr.io"
  - name: image_repository 
    value: "studio" 
  - name: azureSubscription 
    value: "Solution Kit AVOps Demo"  
  - name: appName
    value: "avopsfoxglovestudio"
  - name: tags 
    value: $(Build.BuildId) 
  - name: acr_service_connection 
    value: "acr_service_connection_${{ parameters.env }}" 

stages: 
  - stage: "pullimagefromGHCR" 
    jobs: 
    - job: "imgpullacr" 
      pool: 
        vmImage: "Ubuntu-latest" 
      steps: 
        - script: | 
            docker pull $(ghcr_image) 
          displayName: Pull Foxglove image from GHCR
        - script : |
            docker tag $(ghcr_image) $(containerRegistry)/$(image_repository):$(Build.BuildId)
          displayName: Tagging local Foxglove image
        - task: Docker@2 
          displayName: Login to ACR 
          inputs: 
            command: "login" 
            containerRegistry: $(acr_service_connection) 
        - task: Docker@2 
          displayName: Push image to ACR 
          inputs: 
            command: "push" 
            containerRegistry: $(acr_service_connection) 
            repository: $(image_repository) 
            tags: $(tags)
        - task: AzureWebAppContainer@1
          displayName: 'Azure Web App on Container Deploy'
          inputs:
           azureSubscription: $(azureSubscription)
           appName: $(appName)
           imageName: $(containerRegistry)/$(image_repository):$(Build.BuildId)